# Generated by Django 3.0.4 on 2020-03-11 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('prezzo_totale', models.IntegerField(blank=True, default=0)),
                ('commento', models.CharField(blank=True, max_length=200, null=True)),
                ('data_ora_richiesta', models.DateField(default=datetime.datetime.today, verbose_name='Data e ora di richiesta')),
                ('telefono', models.CharField(max_length=300)),
                ('indirizzo', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
            },
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=300, null=True)),
                ('prezzo', models.CharField(max_length=300, null=True)),
                ('quantita', models.IntegerField(blank=True, default=0)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Ordine')),
            ],
        ),
    ]
