# Generated by Django 3.0.4 on 2020-03-11 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ora_richiesta',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Data e ora di richiesta'),
        ),
    ]
