# Generated by Django 3.0.4 on 2020-03-11 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200311_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ora_richiesta',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 12, 37, 38, 719333), verbose_name='Data e ora di richiesta'),
        ),
    ]
