# Generated by Django 3.0.4 on 2020-03-11 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200311_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='consegnato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='data_ora_richiesta',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 12, 43, 52, 381501), verbose_name='Data e ora di richiesta'),
        ),
    ]
