# Generated by Django 3.0.4 on 2020-03-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200311_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ora_richiesta',
            field=models.CharField(max_length=200),
        ),
    ]
