# Generated by Django 3.0.4 on 2020-03-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('tipo_piatto', models.CharField(choices=[('colazione', 'colazione'), ('pranzo', 'pranzo'), ('cena', 'cena'), ('da bere', 'da bere')], max_length=100)),
                ('ingredienti', models.CharField(max_length=300, null=True)),
                ('prezzo', models.IntegerField(blank=True, default=0)),
                ('commento', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='images/pets')),
            ],
            options={
                'verbose_name': 'Piatto',
                'verbose_name_plural': 'Piatti',
            },
        ),
    ]
